### ISSUE TITLE
A suitable way to consume this DB

### ISSUE THREAD

**Issue by thesp0nge** [rubysec/ruby-advisory-db#134]
Hi there, I really want to move [dawnscanner] (https://github.com/thesp0nge/dawnscanner) to consume this, but I'm puzzled on to do this in an elegant way since it's a very dynamic archive.

My need is that dawnscanner has to check if this archive is updated, download signatures (the YAML files) and than consume them in a review.

How do you suggest me to act? Make a clone each scan can be very bandwith consuming. Having a copy offline and pulling from the scanner sometime it requires me to understand how much updated is the copy.

What do you think packing up the db in a gem or as alternative having an archive version number stored and updated somewhere?

**Comment by phillmv** [comment]
I can't speak to the behaviour exactly since I haven't read the code in a while but I believe https://github.com/rubysec/bundler-audit checks out a local copy and then pulls from it. 

Thus git is responsible for keeping track of updates. I am 90% sure we copied that behaviour when we implemented our own updater.

Does that make sense?

HTH,

**Comment by jeremyolliver** [comment]
Yeah, bundler audit has a git submodule to track this repo which can be updated (via git) without re-installing the gem via the command `bundle-audit update`.

**Comment by mveytsman** [comment]
It looks like @thesp0nge got something working https://github.com/thesp0nge/dawnscanner/blob/fa57547ff30566382941ce2e1f1baa6e9c5f9303/Rakefile
