### ISSUE TITLE
RubySec numbering system

### ISSUE THREAD

**Issue by mveytsman** [rubysec/ruby-advisory-db#224]
We should stop relying on osvdb and cve ids as canonical identifiers as they may not be always present, as in the case where we get a vuln before it's in either db.
- [ ]  Add a new field to the schema, `rubysec-id`
- [ ] Come up with numbering scheme. My suggestion is to model after CVE, ala `RUBYSEC-2016-00001`
- [ ] Add a `rubysec-id`s to past vulns in the database.
- [ ] Come up with policy for generating new id numbes are vulns are added. This should be done by the person with commit bit who's accepting the PR.

**Comment by reedloden** [comment]
How do we track what is the next available ID to use?

For the year assignment, is that the date of the disclosure or date of finding? Depending on that, need to be able to continually add new IDs for previous years as vulnerabilities are found (that we weren't tracking).

Proper CVE-like format would be `RUBYSEC-YYYY-NNNN` where NNNN is always at least 4 numbers, zero-padded (can be increased beyond that over time).

Does `rubysec-id` make sense when we use `cve` and `osvdb` right now? Perhaps just `rubysec` for the field? or `rsid` or something...

**Comment by tarcieri** [comment]
> How do we track what is the next available ID to use?

Each time IDs are assigned, you could check them into a registry file in the repo (perhaps with a note about whom they were assigned to)

**Comment by phillmv** [comment]
>How do we track what is the next available ID to use?

I think we should script something easy to accept PRs with - maybe it'll calc the new id, merge the changes, apply new id then push the merged results, rather than just using GH.

>For the year assignment, is that the date of the disclosure or date of finding?

I vote disclosure. Keep it simple. 

>Does rubysec-id make sense when we use cve and osvdb right now? Perhaps just rubysec for the field? or rsid or something...

I'd propose RBS-YYYY-NNNN and keep it `rubysec` or `rubysec-id`. 

In my heart of hearts, I think it'd be cool to ditch the centrally managed monotonic integer and instead have some kind of hashing scheme to keep id-space management simple.

Suppose we have YYYY- {7 most significant bits of sha1(package, date) (increment by one in case of collision)}. I can't be arsed to calc the probability of collision at our volume but I'm going to guess it's rather low. We still have to write the script to check on merge, but by and large anyone can generate an ID and it becomes valid by being accepted into the repo. (I totally get it if people think that's too much of a pain :P)

**Comment by JonRowe** [comment]
Why not write a script to calculate it and apply as a build step via travis-ci?

**Comment by VanessaHenderson** [comment]
I feel like this is more important now that OSVDB seems to have been down for the last month or so

**Comment by VanessaHenderson** [comment]
Yup, so the OSVDB numbering system certainly won't work anymore. They've shut down,  see https://blog.osvdb.org/2016/04/05/osvdb-fin/

**Comment by postmodern** [comment]
@VanessaHenderson opened issue #251 to discuss triaging the OSVDB shutdown.

**Comment by mveytsman** [comment]
+1

**Comment by mveytsman** [comment]
I made a first pass at a rake task to reserve rubysec ids ala @tarcieri's suggestion

If there's consensus I can assign rubysec ids to everything as a step towards getting rid of OSVDB (#251)

**Comment by reedloden** [comment]
We could also just add support for DWF, which is going to be merged with CVE. We could become our own CNA for DWF. Might be easier.

**Comment by phillmv** [comment]
So I spent sometime thinking about this. The DWF Reed is referring to is the [Distributed Weakness Filing](https://github.com/distributedweaknessfiling) which could use some marketing love if it's to be adopted widely BUT:

If we are to adopt a custom numbering scheme that *should* be backwards compatible with CVE… we might as well become a numbering authority of this system rather than make our own.

Prompted by #256, barring any objections, in the next few days I'll reserve some address space on DWF and set up a mail forwarder for the domain.

**Comment by postmodern** [comment]
:+1: for going with a defacto standard, instead of yet-another-numbering system.

**Comment by reedloden** [comment]
I submitted a PR to get us a block of IDs -- https://github.com/distributedweaknessfiling/DNA-Registry/pull/14

@phillmv, can you set up the e-mail forwarder? or I can help if you're too busy.

**Comment by thesp0nge** [comment]
In order to use a your numbering system in @dawnscanner, are you going to
backport all ruby/gems related CVE?

On 20 May 2016 at 05:25, Reed Loden <notifications@github.com> wrote:

> I submitted a PR to get us a block of IDs --
> distributedweaknessfiling/DNA-Registry#14
> <https://github.com/distributedweaknessfiling/DNA-Registry/pull/14>
>
> @phillmv <https://github.com/phillmv>, can you set up the e-mail
> forwarder? or I can help if you're too busy.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rubysec/ruby-advisory-db/issues/224#issuecomment-220508525>
>



-- 
$ cd /pub
$ more beer

I pirati della sicurezza applicativa: https://codiceinsicuro.it

**Comment by reedloden** [comment]
We would still support CVEs, and in fact, DWF is working closely with CVE, so it may end up that we will get CVE assignments anyway for stuff (just perhaps on a delayed basis, where we can assign DWF ourselves). We're just not going to support any new OSVDB stuff, and we should migrate all the OSVDB stuff to DWF, most likely.

**Comment by reedloden** [comment]
In fact, looks like we're just going to be assigning CVEs (in-)directly (and not DWFs).

We've been approved by DWF and are ready to get CVEs as needed. I'm going to put together a list of vulnerabilities that need a CVE assigned and start getting that done.

**Comment by phillmv** [comment]
That's great, I look forward to figuring that out.

I've been caught in traffic; no one uses info@ rn so I think that can wait till I'm back on Monday.

**Comment by mveytsman** [comment]
I now believe DWF/CVE (or possibly OVE) is the way forward.

The DWF system is undergoing some changes, and I'm in contact with @kurtseifried on getting us set up.

Since I was the one pushing our own numbering system, and don't think that's the right move anymore, I'm closing this issue
